### ISSUE TITLE
re: GetBalanceMulti

### ISSUE THREAD

**Issue by suspectzed** [jfdelgad/etherscanAPI#1]
Good job on this!!!  < best I found.

I cant figure out how to get the getBalanceMulti call working and the help doesnt seem to identify the syntax.

Any help is appreciated.

myapi.getBalanceMulti(<address1>, <address2>)

Not a programmer (admittedly), but strangely, crypto has given me the first "problem" to create a "solution" with programming for me... yes.. even after 2 years of C/C++.  Just never made any $ at it.  

Anyhow, what I get is:
myapi.getBalanceMulti(<variable1>,<variable2>)
TypeError: getBalanceMulti() takes 2 positional arguments but 3 were given

it seems like the api call needs to be formatted to etherscan.io api and expect proper return value.  if you point me at the problem will fork and see if I can fix it.

**Comment by jfdelgad** [comment]
what are you passing to the function? You should pass a list of addresses.

**Comment by suspectzed** [comment]
Ah... a python list.  Ha ha ha...

Like:
address_list = [address1, address2, address3]

Thank you.
