### ISSUE TITLE
Not using API key

### ISSUE THREAD

**Issue by suspectzed** [jfdelgad/etherscanAPI#2]
When I run the example, the API key does not appear to be used by Etherscan and I am hitting request limits in my code to about 1:5seconds (need to use timer.sleep(5) to throttle down).

>>> from etherscanAPI import etherscan
>>>
>>> apikey = '<my api key>'
>>> myapi = etherscan(apikey, 'mainnet') #
>>>
>>> # Get the balance of an account
>>> address = '0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae'
>>> myapi.getBalance(address)
'430341104441599895480972'
>>>

To be more clear:

Although the above code executes, the API stat on etherscan does not indicate I actually used the API key. 

That, combined with the throttle I experience, makes me think that the API key is not being used.

Any idea how to debug that the API key is actually being used through the etherscanAPI.py code?

Thanks,

Andy

**Comment by jfdelgad** [comment]
There was a typo in the code and "apykey" was used instead of "apikey". It is all good now.

**Comment by suspectzed** [comment]
Perfect!  I saw that but wasn't sure if it was right or not.  Changed to http method over https and saw it trying to use my API key in tcpdump, but still had the issue.  Fixed the etherscanAPI.py name and bingo!  Thanks again!
